apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: alert-skjemautfylling
  namespace: skjemadigitalisering
  labels:
    team: skjemadigitalisering
spec:
  receivers: # receivers for all alerts below
    slack:
      channel: '#skjemautfylling-feil-prod'
      prependText: '<!here> | ' # this text will be prepended to the Slack alert title
  alerts:
    - alert: høy feilrate i logger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="skjemautfylling",log_level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="skjemautfylling"}[3m]))) > 10
      for: 3m
      action: "Sjekk loggene til app {{ $labels.log_app }} i Kibana: https://logs.adeo.no/goto/097ce6507d3f5cb2c16f1417d47a9e3d"
    - alert: nav.no/fyllut unavailable
      expr: kube_deployment_status_replicas_available{deployment="skjemautfylling"} == 0
      for: 1m
      action: "Sjekk loggene til app {{ $labels.log_app }} i Kibana: https://logs.adeo.no/goto/097ce6507d3f5cb2c16f1417d47a9e3d"
      sla: respond within 1h, during office hours
      severity: danger
