apiVersion: "monitoring.coreos.com/v1"
kind: PrometheusRule
metadata:
  name: alert-skjemautfylling
  namespace: skjemadigitalisering
  labels:
    team: skjemadigitalisering
spec:
  groups:
    - name: {{ env-name }}
      rules:
        - alert: Høy feilrate i logger
          expr: (100 * sum by (app, namespace) (rate(log_messages_errors{app="skjemautfylling",level=~"Warning|Error"}[3m])) / sum by (app, namespace) (rate(log_messages_total{app="skjemautfylling"}[3m]))) > 10
          for: 3m
          annotations:
            title: "Høy feilrate i logger"
            consequence: "Det kan være mange forskjellige årsaker til feilmeldingene. Se i loggene og undersøk hvorfor det er flere feilmeldinger enn normalt."
            action: {{logs-url}}
          labels:
            service: Fyllut
            namespace: fyllut-sendinn
            special_type_to_use_in_alertmanager_config: {{special-type-to-use-in-alertmanager-config}}
            alert_type: custom
            severity: critical

        - alert: Fyllut er nede
          expr: kube_deployment_status_replicas_available{deployment="skjemautfylling"} == 0
          for: 1m
          annotations:
            title: "Fyllut er nede"
            consequence: "Tjenesten er utilgjengelig for brukere. Undersøk hvorfor poddene er nede."
            action: {{logs-url}}
            sla: respond within 1h, during office hours
          labels:
            service: Fyllut
            namespace: fyllut-sendinn
            special_type_to_use_in_alertmanager_config: "fyllut-sendinn-alerts"
            alert_type: custom
            severity: critical