name: Deploy alerts
run-name: Deploy alerts for Fyllut to dev and prod

on:
  push:
    branches:
      - master
      - auto-deploy-alerts
    paths:
      - '.nais/alerts.yaml'
      - '.nais/dev-alert.yaml'
      - '.nais/prod-alert.yaml'
      - '.github/workflows/alert-deploy.yaml'
permissions:
  id-token: write

jobs:
  dev-deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/alerts.yaml
          VARS: .nais/dev-alert.yaml

  prod-deploy:
    name: Deploy to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts.yaml
          VARS: .nais/prod-alert.yaml
