name: "Deploy 'fyllut'"
on:
  workflow_dispatch:
  push:
    branches:
      - mainformio
env:
  IMAGE: "docker.pkg.github.com/${{ github.repository }}/fyllut:${{ github.sha }}"
  PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
  PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
  PUSHER_APP_SECRET: ${{ secrets.PUSHER_APP_SECRET }}
  PUSHER_APP_CLUSTER: ${{ secrets.PUSHER_APP_CLUSTER }}


jobs:
  package-and-push-fyllut:
    name: "Package 'fyllut'"
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: "actions/setup-node@v1"
        with:
          node-version: '14.17.0'
      - name: build shared-components
        working-directory: ./skjemabygging-formio/packages/shared-components
        run: yarn install --frozen-lockfile && yarn build
      - name: "Frontend: prepare local dependencies"
        working-directory: ./skjemabygging-formio
        run: node bin/deploy-context.mjs ./packages/fyllut --replace
      - name: "Frontend: install dependencies and build"
        working-directory: ./skjemabygging-formio/packages/fyllut
        run: |
          yarn install --frozen-lockfile
          REACT_APP_GIT_VERSION=${{ github.sha }} yarn build:prod
      - name: "Backend: prepare local dependencies"
        working-directory: ./skjemabygging-formio
        run: node bin/deploy-context.mjs ./packages/fyllut/server --replace
      - name: "Backend: install dependencies"
        working-directory: ./skjemabygging-formio/packages/fyllut/server
        run: yarn install --frozen-lockfile
      - name: "Find SHA for new version"
        working-directory: ./skjemabygging-formio/packages/fyllut
        run: echo ::set-output name=SHA::$(git rev-parse HEAD)
        id: find-skjemautfylling-formio-sha
      - name: "Copy skjema and translation into docker build context"
        run: |
          cp -r ./skjema ./skjemabygging-formio/packages/fyllut/temp-skjema
          cp -r ./translation ./skjemabygging-formio/packages/fyllut/temp-translation
        working-directory: .
      - name: "Build and publish Docker formio-image"
        working-directory: ./skjemabygging-formio/packages/fyllut
        run: >
          docker build --pull --tag ${IMAGE}
          --build-arg git_sha=${{ github.sha }}
          --build-arg monorepo_git_sha=${{ steps.find-skjemautfylling-formio-sha.SHA }}
          --build-arg skjema_dir=temp-skjema
          --build-arg translation_dir=temp-translation .
          && echo ${{ secrets.GITHUB_TOKEN }} | docker login
          --username ${{ github.repository }} --password-stdin https://docker.pkg.github.com
          && docker push ${IMAGE}
      - name: Notify job failure
        if: ${{ failure() }}
        run: cat $GITHUB_EVENT_PATH | bin/trigger-workflow-message.mjs build-aborted
  deploy-fyllut-to-labs:
    name: "Deploy 'fyllut' to labs"
    needs: "package-and-push-fyllut"
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Deploy to LABS"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "labs-gcp"
          "RESOURCE": "./skjemabygging-formio/packages/fyllut/.nais/config.yaml"
          "VARS": "./skjemabygging-formio/packages/fyllut/.nais/labs.yaml"
      - name: Notify job success
        if: ${{ success() }}
        run: cat $GITHUB_EVENT_PATH | bin/trigger-workflow-message.mjs skjemautfyller-deployed
      - name: Notify job failure
        if: ${{ failure() }}
        run: cat $GITHUB_EVENT_PATH | bin/trigger-workflow-message.mjs build-aborted
