name: "Deploy 'fyllut'"
on:
  push:
    branches:
      - master
env:
  IMAGE: "docker.pkg.github.com/${{ github.repository }}/fyllut:${{ github.sha }}"
  PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
  PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
  PUSHER_APP_SECRET: ${{ secrets.PUSHER_APP_SECRET }}
  PUSHER_APP_CLUSTER: ${{ secrets.PUSHER_APP_CLUSTER }}


jobs:
  package-and-push-fyllut:
    name: "Package 'fyllut'"
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: "actions/setup-node@v1"
        with:
          node-version: '14.17.0'
      - name: "Install deps for notification message"
        run: yarn install
      - name: "Build shared-components"
        working-directory: ./skjemabygging-formio/packages/shared-components
        run: yarn install --frozen-lockfile && yarn build
      - name: "Frontend: prepare local dependencies"
        working-directory: ./skjemabygging-formio
        run: node bin/deploy-context.mjs ./packages/fyllut --replace
      - name: "Frontend: install dependencies and build"
        working-directory: ./skjemabygging-formio/packages/fyllut
        run: yarn install --frozen-lockfile && yarn build:prod
        env:
          REACT_APP_GIT_VERSION: ${{ github.sha }}
      - name: "Backend: prepare local dependencies"
        working-directory: ./skjemabygging-formio
        run: node bin/deploy-context.mjs ./packages/fyllut/server --replace
      - name: "Backend: install dependencies"
        working-directory: ./skjemabygging-formio/packages/fyllut/server
        run: yarn install --frozen-lockfile
      - name: "Find SHA for new version"
        working-directory: ./skjemabygging-formio/packages/fyllut
        run: echo ::set-output name=SHA::$(git rev-parse HEAD)
        id: find-skjemautfylling-formio-sha
      - name: "Copy forms and translations into docker build context"
        run: |
          cp -r ./forms ./skjemabygging-formio/packages/fyllut/temp-forms
          cp -r ./translations ./skjemabygging-formio/packages/fyllut/temp-translations
        working-directory: .
      - name: "Build and publish Docker image"
        working-directory: ./skjemabygging-formio/packages/fyllut
        run: >
          docker build --pull --tag ${IMAGE}
          --build-arg git_sha=${{ github.sha }}
          --build-arg monorepo_git_sha=${{ steps.find-skjemautfylling-formio-sha.outputs.SHA }}
          --build-arg skjema_dir=temp-forms
          --build-arg translation_dir=temp-translations .
          && echo ${{ secrets.GITHUB_TOKEN }} | docker login
          --username ${{ github.repository }} --password-stdin https://docker.pkg.github.com
          && docker push ${IMAGE}
      - name: "Notify job failure"
        if: ${{ failure() }}
        run: cat $GITHUB_EVENT_PATH | bin/trigger-workflow-message.mjs build-aborted
  deploy-fyllut-to-prod:
    name: "Deploy 'fyllut' to prod"
    needs: "package-and-push-fyllut"
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Install deps for notification message"
        run: yarn install
      - name: "Deploy to prod"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "prod-gcp"
          "RESOURCE": "./skjemabygging-formio/packages/fyllut/.nais/config.yaml"
          "VARS": "./skjemabygging-formio/packages/fyllut/.nais/prod.yaml"
      - name: "Notify job success"
        if: ${{ success() }}
        run: cat $GITHUB_EVENT_PATH | bin/trigger-workflow-message.mjs skjemautfyller-deployed
      - name: "Notify job failure"
        if: ${{ failure() }}
        run: cat $GITHUB_EVENT_PATH | bin/trigger-workflow-message.mjs build-aborted
