name: 'Publiser ressurs'
on:
  workflow_dispatch:
    inputs:
      resourceName:
        description: name of the resource
        required: true
      encodedJson:
        description: json zlib compressed and base 64 encoded
        required: true
env:
  PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
  PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
  PUSHER_APP_SECRET: ${{ secrets.PUSHER_APP_SECRET }}
  PUSHER_APP_CLUSTER: ${{ secrets.PUSHER_APP_CLUSTER }}
jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TEAM_ACCESS_TOKEN }}
      - uses: "actions/setup-node@v1"
        with:
          node-version: '14.17.0'
      - name: "Update resource"
        working-directory: resources
        run: echo ${{github.event.inputs.encodedJson}} | base64 -d | gzip -d > ${{ github.event.inputs.resourceName }}.json
      - name: "Commit changes"
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add resources
          git commit -m "[resources] publiserer ${{ github.event.inputs.resourceName }}"
      - name: "Push changes"
        run: git push
      - name: Notify job failure
        if: github.ref == 'refs/heads/master' && failure()
        working-directory: ./skjemabygging-formio
        run: |
          yarn && yarn build:scripts
          cat $GITHUB_EVENT_PATH | node packages/scripts/dist/trigger-workflow-message.mjs publish-resource-aborted
