name: 'Publiser skjemadefinisjoner, oversettelser og fyllut'
on:
  workflow_dispatch:
    inputs:
      formJsonFileTitle:
        description: name of the form.json schema
        required: true
      formDescription:
        description: short description of the form, to be included in commit message
        required: false
      encodedFormJson:
        description: Form.io json schema zlib compressed and base 64 encoded
        required: true
      encodedTranslationJson:
        description: translations for the form zlib compressed and base 64 encoded
        required: false
      monorepoGitHash:
        description: git hash of the monorepo
        required: true
env:
  PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
  PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
  PUSHER_APP_SECRET: ${{ secrets.PUSHER_APP_SECRET }}
  PUSHER_APP_CLUSTER: ${{ secrets.PUSHER_APP_CLUSTER }}
jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TEAM_ACCESS_TOKEN }}
      - uses: "actions/setup-node@v1"
        with:
          node-version: '14.17.0'
      - name: "Update forms"
        working-directory: forms
        run: echo ${{github.event.inputs.encodedFormJson}} | base64 -d | gzip -d > ${{ github.event.inputs.formJsonFileTitle }}.json
      - name: "Update translations"
        if: github.event.inputs.encodedTranslationJson
        working-directory: translations
        run: echo ${{github.event.inputs.encodedTranslationJson}} | base64 -d | gzip -d > ${{ github.event.inputs.formJsonFileTitle }}.json
      - name: "Update submodule"
        run: git submodule update --init --force
      - name: "Checkout desired submodule commit"
        working-directory: skjemabygging-formio
        run: |
          ls -l
          git checkout ${{ github.event.inputs.monorepoGitHash }}
      - name: "Commit changes"
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add forms translations skjemabygging-formio
          git commit -m "[publisering] skjema ${{ github.event.inputs.formDescription || github.event.inputs.formJsonFileTitle }}, monorepo ref: ${{ github.event.inputs.monorepoGitHash }}"
      - name: "Push changes"
        run: git push
      - name: Notify job failure
        if: github.ref == 'refs/heads/master' && failure()
        working-directory: ./skjemabygging-formio
        run: |
          yarn && yarn build:scripts
          cat $GITHUB_EVENT_PATH | node packages/scripts/dist/trigger-workflow-message.mjs publish-aborted

