name: "Test usage of fyllut base docker image"

on:
  push:
    branches:
      - test-publishing2

env:
  IMAGE: "ghcr.io/${{ github.repository }}/test-fyllut-app:${{ github.sha }}"
  IMAGE_FYLLUT_BASE: "ghcr.io/navikt/skjemabygging-formio/${{ github.ref == 'refs/heads/master' && 'fyllut-base' || 'fyllut-base-dev' }}"

jobs:
  package-and-push-fyllut:
    name: "Package 'fyllut'"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read monorepo commit sha
        id: monorepo
        run: echo ::set-output name=sha::$(cat MONOREPO)
      - name: Login to GitHub Package Repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and publish Docker image"
        run: >
          docker build --pull --tag ${IMAGE}
          --build-arg image_fyllut_base=${IMAGE_FYLLUT_BASE}
          --build-arg monorepo_git_sha=${{ steps.monorepo.outputs.sha }}
          --build-arg git_sha=${{ github.sha }}
          --build-arg skjema_dir=forms
          --build-arg translation_dir=translations
          --build-arg resources_dir=resources .
          && docker push ${IMAGE}
