name: "Trigger dev deploy"
on:
  workflow_dispatch:
    inputs:
      monorepoGitHash:
        description: git hash of the monorepo
        required: true

jobs:
  publish:
    name: "Prepare deploy to dev"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.TEST_TOKEN }}
      - name: "Fetch latest forms and translations from master, ignore merge conflicts due to monorepo reference"
        run: git merge origin/master || git add MONOREPO
      - name: "Update MONOREPO reference"
        run: echo -n ${{ github.event.inputs.monorepoGitHash }} > MONOREPO
      - name: "Add and commit changes"
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: "MONOREPO"
          author_name: Github Actions
          default_author: github_actions
          message: "[${{ github.ref }}] monorepo ref: ${{ github.event.inputs.monorepoGitHash }}"
