name: "Trigger dev deploy"
on: push
jobs:
  publish:
    name: "Prepare deploy to dev"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.SKJEMADIGITALISERING_WORKFLOW_TOKEN }}
      - name: "Git config user email and name"
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
      - name: "Fetch latest forms and translations from master, ignore merge conflicts due to monorepo reference"
        run: git merge origin/master || git add MONOREPO
      - name: "Update MONOREPO reference"
        run: echo -n 49cb847c964b34b2027d42a5cc6efcfa534d171f > MONOREPO
      - name: "Add MONOREPO"
        run: git add MONOREPO
      - name: "No unstaged changes should exist, quit otherwise"
        run: git diff --quiet
      - name: "Commit changes"
        run: |
          git commit -m "[${{ github.ref }}] monorepo ref: 49cb847c964b34b2027d42a5cc6efcfa534d171f"
      - name: "Push changes"
        run: git push
